/** Brief hover hints for text fields across the app. */
export const FIELD_HINTS = {
  courseTitle: "Full course name.",
  courseCode: "Course code (optional).",
  creditUnits: "Credit units.",
  lecturerName: "Lecturer name.",
  email: "Sign-in email.",
  password: "At least 6 characters.",
  programmeOfStudy: "Your degree or programme.",
  semesterName: "Term name, e.g. Harmattan 2026.",
  semesterStartDate: "Semester start date.",
  semesterEndDate: "Semester end date.",
  copyCoursesFrom: "Copy courses from a prior term.",
  gradeLetter: "Letter grade when set.",
  calculatorCourseName: "Course name.",
  calculatorCreditUnits: "Credit units.",
  calculatorTotalCredits: "Total credits this term.",
  timetableStartHour: "First grid hour (24h).",
  timetableEndHour: "Last grid hour (24h).",
  timetableCourse: "Course for this slot.",
  timetableNewCourseName: "New course name.",
  timetableLecturer: "Lecturer name.",
  timetableLocation: "Room or link.",
  timetableDuration: "Hours this block spans.",
  topicTitle: "Topic name.",
  topicStatus: "Not started, taught, or mastered.",
  topicNotes: "Revision notes.",
  suggestedTopicLine: "Edit before adding.",
  addTopicTitle: "New topic name.",
  activeSemester: "Semester to view and edit.",
} as const;
